#+title: First Draft
The wandering lifestyle always felt natural to me; I never wanted to root myself in one place, and miss out on the rest of the galaxy, but instead travel from planet to planet, gathering insights from a wide variety of cultures. But even travelling would not remove the  fundamental ways of thinking that my culture had rooted in me. When I first got my Omni-Ship, I wanted to start out by taking a "pilgrimage" or sorts to the capitals of the [[Perseus Princes]].

The [[Perseus Princes]] (it should be "Perseus Principalities", but yeah I - the author - will fix this) are the meta-civilization that my home planet - Foristr, a thoroughly beautiful world that I am grateful to be born on - has aligned with. The Perseus Princes have a philosophy of intertoposophic interconnection, evolutionary and mind diversity, and even other branes and ideas about what may be in them! And this was thanks to Fractalism.

Fractalism - with its elegant mathematics - has held my interest since I first knew of it. I have been interested in art - first, ChemoArt, then GeoArt and even MathArt - ever since I could contribute to the maintenance of my forest.
